# Generated by Django 4.2.7 on 2023-11-02 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Musician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200, verbose_name='Email')),
                ('main_instrument', models.CharField(choices=[('AG', 'Acoustic Guitar'), ('EG', 'Electric Guitar'), ('BG', 'Bass Guitar'), ('DR', 'Drums/Percussion'), ('VO', 'Vocals/Singing'), ('PI', 'Piano/Keyboard'), ('VI', 'Violin/Viola'), ('CE', 'Cello'), ('FH', 'French Horn'), ('SA', 'Saxophone'), ('TR', 'Trumpet'), ('TB', 'Trombone'), ('O', 'Other')], max_length=200)),
            ],
        ),
    ]
