# Generated by Django 4.2.7 on 2023-11-05 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Piece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('genre', models.CharField(max_length=200)),
                ('piece_type', models.CharField(choices=[('CR', 'Concert/Performance Recording'), ('OS', 'Original Song'), ('CS', 'Cover Song'), ('O', 'Other')], max_length=200)),
                ('musician', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='portfolio_app.musician')),
            ],
        ),
    ]
