# Generated by Django 4.2.7 on 2023-11-05 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0002_piece'),
    ]

    operations = [
        migrations.AddField(
            model_name='piece',
            name='mp3_file',
            field=models.FileField(null=True, upload_to='music/mp3/'),
        ),
    ]
