# Generated by Django 4.2.7 on 2023-11-21 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0005_alter_piece_mp3_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='musician',
            name='username',
            field=models.CharField(default='username', max_length=15),
        ),
    ]
